// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wyklad11.Models;

namespace wyklad11.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20200616164941_AddedStudiesTable")]
    partial class AddedStudiesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wyklad11.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("wyklad11.Models.Studies", b =>
                {
                    b.Property<int>("IdStudies")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("IdStudies");

                    b.ToTable("Studies");

                    b.HasData(
                        new { IdStudies = 1, Description = "AAA", Name = "IT" },
                        new { IdStudies = 2, Description = "BBB", Name = "Graphic Design" }
                    );
                });

            modelBuilder.Entity("wyklad11.Models.Subject", b =>
                {
                    b.Property<int>("IdSubject")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("TotalPoints");

                    b.HasKey("IdSubject");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("wyklad11.Models.Student", b =>
                {
                    b.HasBaseType("wyklad11.Models.Person");

                    b.Property<int?>("IdSubject");

                    b.Property<string>("IndexNumber");

                    b.HasIndex("IdSubject");

                    b.ToTable("Student");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("wyklad11.Models.Student", b =>
                {
                    b.HasOne("wyklad11.Models.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("IdSubject");
                });
#pragma warning restore 612, 618
        }
    }
}
